version: '3.3'

services:
  test:
    build: .
    depends_on:
      - db
    # https://github.com/ufoscout/docker-compose-wait
    command: sh -c "/wait && npm run test"
    environment:
      NODE_ENV: development
      MYSQL_HOST: "db"
      MYSQL_PORT: 3306
      MYSQL_DATABASE: 'testdb'
      MYSQL_USER: 'tester'
      MYSQL_PASSWORD: 's3cur3'
      WAIT_HOSTS: "db:3306"
      WAIT_HOSTS_TIMEOUT: 300
      WAIT_SLEEP_INTERVAL: 2
      WAIT_HOST_CONNECT_TIMEOUT: 30

  db:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_DATABASE: 'testdb'
      MYSQL_USER: 'tester'
      MYSQL_PASSWORD: 's3cur3'
      MYSQL_ROOT_PASSWORD: 's3cur3'
    ports:
      - '3306:3306'
    expose:
      - '3306'
